export const CUSTOM_HEADER_PROJECTS_ID = 'x-projects-id';
export const CUSTOM_HEADER_PROJECTS_ID_NOT_APPLICABLE = 'N/A';

export const CUSTOM_HEADER_PROJECTS_ID_NOT_APPLICABLE_HEADER = {
  [CUSTOM_HEADER_PROJECTS_ID]: CUSTOM_HEADER_PROJECTS_ID_NOT_APPLICABLE,
};
